[platformio]
default_envs = cardputer

[env:cardputer]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

board_build.arduino.memory_type = qio_opi
board_build.partitions = default_8MB.csv

build_unflags = 
    -std=gnu++11
    -fno-exceptions

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM=1
    -DCONFIG_SPIRAM_USE=1
    -DCORE_DEBUG_LEVEL=3
    -DM5CARDPUTER
    -std=gnu++17
    -fexceptions
    -Wall
    -DMSGPACK_USE_BOOST=OFF
    -DRNS_USE_FS
    -DUSTORE_USE_NOOPFS
    -DRNS_DEFAULT_ALLOCATOR=RNS_HEAP_ALLOCATOR
    -DRNS_CONTAINER_ALLOCATOR=RNS_HEAP_ALLOCATOR
    -DNDEBUG

lib_deps = 
    m5stack/M5Cardputer @ ^1.0.3
    m5stack/M5Unified @ ^0.2.0
    file:///home/pondycrane/microReticulum
    https://github.com/attermann/microStore.git
    LittleFS

lib_ldf_mode = deep

extra_scripts = 
